### ISSUE TITLE
Expose chunker

### ISSUE THREAD

**Issue by somebody1234** [hypercore-protocol/hyperdrive#165]
So the client can modify the chunks before they are written and read, or chunk the data differently

**Comment by joehand** [comment]
AFAIK the chunk size is up to the client already if you use the [write stream](https://github.com/mafintosh/hyperdrive#var-stream--archivecreatewritestreamname-options). You should be able to set the chunk size in your read stream and hyperdrive will use whatever you pipe to `createWriteStream`.

**Comment by somebody1234** [comment]
That isn't the reason why I want the chunker exposed though

**Comment by mafintosh** [comment]
I'm ok adding a chunker option that is a through stream that all data is
piped through internally

**Comment by somebody1234** [comment]
@mafintosh Yeah that would work
