### ISSUE TITLE
Reuse existing identity key on startup

### ISSUE THREAD

**Issue by fmsouza** [hypercore-protocol/hyperdrive#307]
I looked around the docs and issues list for a way to reuse an existing master key on the hyperdrive startup, but found nothing. Is it possible? And if so, how to do it?

Use case for that would be using the same identity while accessing your data on the network in different devices. Imagine an hyperdrive-based "Twitter". I want to post from several different devices (computer, phone, etc.) but using the same identity, so I won't need to have a separate feed of things I posted for each device I am using.

**Comment by Grim-pyc** [comment]
Did you ever find an answer?
